swagger: '2.0'
info:
  description: This is an API documentation for the Secrets App
  version: "1"
  title: Vaults App
# Added by API Auto Mocking Plugin
host: virtserver.swaggerhub.com
# basePath: /ksenia2/Vaults-API/1
# global level of security for whole API

securityDefinitions:
   APIKeyHeader:
     type: apiKey
     in: header
     name: X-API-Key
   basicAuth:
     type: basic
     
# Global security (applies to all operations):
security: # APIKeyHeader AND basicAuth
  - APIKeyHeader: []
    basicAuth: [] 
    
  
tags:
- name: User
  description: "Registration"
- name: Vault
  description: Create and use vaults 
- name: Deposit
  description: upload files to vault
- name: Login
  description: user logs in to system
- name: Secrets
  description: user in vault session
schemes:
 - "https"

paths:

  /login:
    get:
      tags:
        - Login
      produces:
        - "application/json"
      responses:
         '200':
           description: login form sent
         '401':
           description: you are already logged in 
         '429':
           description: stop trying to crash us!
         '503':
           description: service currently unavailable
         default:  
           description: Something went wrong.
           
    post:
        tags: 
        - Login
        summary: send user login details
        produces:
          - "application/json"
        parameters:
           - in: body
             name: userDetails
             description: Starting a login session.
             schema:
                $ref: '#/definitions/user'  
        responses:
           '201':
             description: User sucessfully loged in.
             schema:
               type: boolean
               
           '400':
             description: Bad request. User ID must be an integer and bigger than 0.
               Please change your input and try again.
           '401':
             description: One ot more of the provided credentials dontmatch. Please change your input and try again. 
           '429':
               description: too many requests
           '503':
               description: service unavailable
           

  /me:
    patch:
      tags:
        - User
      summary: "edit user"
      produces:
       - "application/json"
      parameters:
       - in: path
         name: userId
         type: string
         required: true
         
      responses:
        '200':
          description: user updated
        '400':
          description: Bad request. User ID must be an integer and bigger than 0.
            Please change your input and try again. 
        '404':
          description: no such user
        '429':
          description: too many requests
        '503':
          description: service is currentlly not available 

    delete:
      tags:
      - User
      summary: "delete user"
      parameters:
       - in: path
         name: userId
         type: string
         required: true
      responses:
        '200':
          description: user deleted
        '400': 
          description: token invalid
        '406':
           description: Not Acceptable  
        '429':
           description: too many requests
        '503':
           description: service unavailable   
           
  /user/{userId}:      
    get:
      tags:
        - User
      summary: "Get user by id"
      produces:
       - "application/json"
      parameters:
       - in: path
         name: userId
         type: string
         required: true
      responses:
          '200':
            description: user retrived
            schema:
                type: object
                properties:
                    username:
                      type: string
                      description: The user name.
          '400':
            description: Bad request. User ID must be an integer and bigger than 0.
              Please change your input and try again. 
          '404':
            description: users not found - registry is empty.
             Please change your input and try again. 
          '429':
           description: too many requests
          '503':
            description: service is currentlly not available 

          
  /user/new:
    get:
      tags:
        - User
      summary: "get registry form"
      security: []   # No security
      produces:
        - "application/json"
      responses:
         '201':
           description: send registration form
         '400':
           description: Bad request. User ID must be an integer   and bigger than 0.
             Please change your input and try again. 
         '404':
           description: user not found. 
         '406':
           description: Not Acceptable  
         default:  
           description: Something went wrong.
  /user:         
    post:
     tags:
        - User
     summary: "Create user"
     security: []   # No security
     produces:
      - "application/json"
     parameters:
       - in: body
         name: userDetails
         description: The user to create.
         schema:
            $ref: '#/definitions/user'  
     responses:
       '201':
         description: An user object Created.
         schema:
           $ref: '#/definitions/user'
           # should token returning from server should be described here?
       '400':
         description: Bad request. User ID must be an integer and bigger than 0.
           Please change your input and try again. 
       '429':
           description: too many requests
       '503':
           description: service unavailable

    


  /vault:
    post:
     tags:
        - Vault
     summary: "Create vault"
     produces:
      - "application/json"
     parameters:
      - in: body
        name: body
        description: Created vault object
        required: true
        schema:
          $ref: '#/definitions/vault'
         
     responses:
          '201':
            description: A vault object Created.
            schema:
              type: object
              properties:
                id:
                  type: string
                  description: The vault ID.
                location:
                  type: object
                  description: latitude-longitude coordinates
                owner:
                  type: string
                  description: jumbled and uglified username/key
          '400':
            description: Bad request. User ID must be an integer and bigger than 0.
              Please change your input and try again.
          '406':
            description: Not Acceptable  
          default:  
            description: Something went wrong.
  
  /vault:
    patch:
      tags:
      - Vault
      summary: Check if this is my vault. if true, it possible to view files, deposit/withdrowl.
      parameters:
       - in: header
         name: location
         type: array
         description: location of the logedin user's vault
         required: true
      produces:
       - boolean
      description: true/false statment weather the vault is mine or not
       
      responses:
        '200': 
          description: this is your vault
        '400':
          description: one or more parameters is missing. Please enable location access.
        '401':
          description: Please register and login.
        '429':
          description: too many requests
        '503':
          description: services currently offline            
    
    
  /vault/{vaultId}:        
    delete:
      tags:
      - Vault
      summary: delete vault [and contents?]
      parameters:
        - in: path
          name: vaultId
          type: string
          description: specific vault id
          required: true 
      responses:
        '200': 
          description: vault deleted
        '400':
          description: one or more parameters is missing
        '401':
          description: you do not have authorization to change this vault
        '404':
          description: vault not found
        '429':
          description: too many requests
        '503':
          description: services currently offline
          
  /vault/new:
    get:
      tags:
        - Vault
      summary: "create new vault form"
      produces:
        - "application/json"
      responses:
         '201':
           description: new vault form was sent
         '401':
           description: Unauthorized. Please register and login.
         '429':
           description: too many requests
         '503':
           description: service unavailable   
         
         default:  
           description: Something went wrong.





definitions:

  user:
    type: object
    required:
      - firstName
      - lastName
      - email
      - password
    properties:
      id:
        type: integer
        format: int64
      username:
        type: string
      email:
        type: string
      password:
        type: string
        
  vault:
    type: object
    required:
      - owner
      - location
    properties:
      id:
        type: integer
        format: int64
      owner:
        type: string
      location:
        type: object
        required:
          - longditude
          - latitude
        properties:
          longditude:
            type: string
          latitude:
            type: string
  secret:
   type: object
   required:
     - title
     - content
        

# Added by API Auto Mocking Plugin
# basePath: /startup-booste/vault-test/1
# Added by API Auto Mocking Plugin
basePath: /startup-booste/vault-test/1